---
title: "Leaflet Map with Shape Files"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r libraries}
library(maps)
library(mapproj)
library(leaflet)
library(rgdal)
```

```{r load_data}
suppressWarnings({
# Load in shapefiles from FCC https://www.fcc.gov/general/oklahoma-enhanced-lifeline-support-maps
aesa <- readOGR(dsn = "./data", layer = "adopted_enhanced_support_area", verbose = F)
chero <- readOGR(dsn = "./data/", layer = "cherokee_outlet",verbose = F)

# Load in GEOJSON of OK county lines from http://catalog.opendata.city/dataset/oklahoma-counties-polygon/resource/75b87ccf-da9e-464e-814b-16985041d2ca
okgj <- readOGR(dsn="./data/okcounties.geojson", layer="OGRGeoJSON",verbose = F)

df_rds2 <- readRDS("./data/okdem2.RDS")
okgj@data <- df_rds2
})
```

```{r leaflet_plot}

  var <- okgj@data$incomeBelowPoverty
  
col <- "YlGnBu"
legend.title <- "% Below Poverty Line"

# generate vector of fill colors for map
pal <- colorNumeric(palette = col, domain = var)

# create pop-up on click
county_popup <-
  paste0(
    "<strong>Name: </strong>",
    okgj$name,
    "<br><strong>",
    legend.title,
    ", 2014: </strong>",
    var * 100,
    "%"
  )

# produce base map
map <- leaflet(data = okgj) %>% addTiles()

# add specs
map %>%
  addPolygons(
    stroke = FALSE,
    smoothFactor = 0.2,
    fillOpacity = 0.8,
    fillColor = ~ pal(var),
    weight = 1,
    popup = county_popup
  ) %>%
  addLegend(
    "bottomleft",
    pal = pal,
    values = ~ var,
    title = legend.title,
    labFormat = labelFormat(suffix = "%"),
    opacity = 1
  ) %>%
  addPolylines(data = aesa,
               color = "red",
               popup = "Enhanced Support Area") %>%
  addPolylines(data = chero,
               color = "blue",
               popup = "Cherokee Outlet")

```


# Attribution

The code to mae this visualisation is based on the work of Raphael Leung, and the data has also been taken from the same source; https://github.com/lcyraphael/ok_shinymap. Note that this data and code were generated for his submission to the Oxford University OxTalent 2016 competition.